{"version":3,"file":"js/9613.aa9d7ccf.js","mappings":"oHAAA,uW","sources":["webpack://myblog/./src/assets/md/python/content/005-异常处理.md"],"sourcesContent":["export default \"## **异常处理**\\r\\n\\r\\n- `try-except-finally` 结构。\\r\\n- 自定义异常类。\\r\\n\\r\\n```python\\r\\ntry:\\r\\n    num = int(input(\\\"请输入一个数字: \\\"))\\r\\n    result = 10 / num\\r\\nexcept ValueError:\\r\\n    print(\\\"输入无效，请输入一个数字！\\\")\\r\\nexcept ZeroDivisionError:\\r\\n    print(\\\"除数不能为零！\\\")\\r\\nelse:\\r\\n    print(f\\\"结果是: {result}\\\")\\r\\nfinally:\\r\\n    print(\\\"这是 finally 块，总会执行。\\\")\\r\\n```\";"],"names":[],"sourceRoot":""}